services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app/data:/app/app/data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    platform: linux/amd64
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
